plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Gifty Gracelin I\\Downloads\\wish-blossom-vibe-mainzip\\wish-blossom-vibe-main\\wish-blossom-vibe-main\\dist\\client"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]